services:
  mysql-db:
    image: mysql:8.0
    container_name: attendance_db
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - attendance-svc-network
    ports:
      - 3306:3306
    restart: always

  app:
    container_name: attendance_svc_api
    build: .
    depends_on:
      - mysql-db
    volumes:
      - attendance-data:/var/lib/mysql
    networks:
      - attendance-svc-network
    ports:
      - "3001:3001"
    environment:
      DB_TYPE: ${DB_TYPE}
      NODE_ENV: ${NODE_ENV}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: attendance_db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      NODE_PORT: ${NODE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_FROM_EMAIL: ${SENDGRID_FROM_EMAIL}
      SENDGRID_FROM_NAME: ${SENDGRID_FROM_NAME}
      SENDGRID_REPLY_TO_EMAIL: ${SENDGRID_REPLY_TO_EMAIL}
      SENDGRID_REPLY_TO_NAME: ${SENDGRID_REPLY_TO_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      
    restart: always

volumes: 
  attendance-data: {}
networks:
  attendance-svc-network:
    driver: bridge
   